name: Fake GitHub Activity

on:
  schedule:
    - cron: '0 12 * * *'  # tous les jours à midi (UTC)
  workflow_dispatch:  # pour lancer manuellement

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "mbarek-bot"
          git config user.email "mbark.bik@gmail.com"

      - name: Make a fake commit
        run: |
          echo "$(date) - Auto activity" >> activity.log
          git add activity.log
          git commit -m "Daily activity"
          git push
